# Generated by Django 4.0.4 on 2022-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_order_transaction_id_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified_customer',
            field=models.BooleanField(default=False),
        ),
    ]
