# Generated by Django 4.0.4 on 2022-05-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_order_notified_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
