# Generated by Django 4.0.4 on 2022-05-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_order_session_key_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=14)),
                ('province', models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('KIGALI', 'Kigali'), ('WEST', 'West')], default='Kigali', max_length=20)),
                ('district', models.CharField(choices=[('Gasabo', 'Gasabo'), ('Kicukiro', 'Kicukiro'), ('Huye', 'Huye'), ('Musanze', 'Musanze')], default='Gasabo', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='vicinity',
        ),
        migrations.CreateModel(
            name='AnonymousPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255)),
                ('payment_method', models.CharField(default='mobilemoney', max_length=50)),
                ('status', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(default='RWF', max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('amount_settled', models.PositiveIntegerField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.anonymousaddress')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.order')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousPayedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('token', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.anonymouspayment')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('notified_customer', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.anonymousaddress')),
                ('products', models.ManyToManyField(to='books.book')),
            ],
        ),
    ]
