# Generated by Django 4.0.4 on 2022-05-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_anonymousaddress_remove_address_vicinity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousorder',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouspayment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.anonymousorder'),
        ),
    ]
