# Generated by Django 3.2.8 on 2021-10-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211030_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/blog/default.jpg', null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='/blog/default_thumb.jpg', null=True, upload_to='blog/thumnails'),
        ),
    ]
