# Generated by Django 3.2.8 on 2021-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211030_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
