# Generated by Django 3.2.8 on 2021-11-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211129_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['approved', '-created_on'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Menya byose', max_length=50),
            preserve_default=False,
        ),
    ]
