# Generated by Django 3.2.8 on 2021-12-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211130_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visits',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='blog/default.jpg', null=True, upload_to='blog'),
        ),
    ]
