# Generated by Django 3.2.8 on 2023-01-17 17:51

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_author_profile_picture_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='picture1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='picture1'),
        ),
        migrations.AddField(
            model_name='service',
            name='picture2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='picture2'),
        ),
    ]
