name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DB_USER: db
      DB_PORT: 5432
      DB_HOST: localhost
      DB_NAME: postgress
      DB_PASS: hello
      FLUTTER_SECRET: FLWSECK_TEST-key
      FLUTTER_PUBLIC: FLWPUBK_TEST-key
      DATABASE_URL: postgres://db:hello@localhost:5432/db
      MODE: test
      EMAIL_USER: info@password.com
      EMAIL_PASS: info
      DEBUG: False
      cloud_name : <cloudinary name>
      api_key: <This is just a key>
      api_secret: <Here goes the secret>

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
