name: DEPLOY
on:
  # Runs on push to the main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    # deploy to heroku main app
    concurrency: 
      group: heroku_deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "isaniro"
          heroku_email: "info@isaniro.com"